### ISSUE TITLE
As an operator I want to be able to assign my promotion a name

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#103]
- [ ] User can type an alpha numeric description of their promotion

- [ ] 280 character limit for name

Mockups: (Promotion Detail) https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523
![Promotion Detail Page_Create.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/60a77d35-7ce7-4010-b72b-87f13b724ec7)

**Comment by vannguyenn** [comment]
@brendan-shea-pm  Do promotion names have to be unique across the shop?

**Comment by vannguyenn** [comment]
@brendan-shea-pm, how do users land on this page? Do we have a Create button somewhere?

**Comment by brendan-shea-pm** [comment]
> @brendan-shea-pm Do promotion names have to be unique across the shop?

Names can be duplicates

> @brendan-shea-pm, how do users land on this page? Do we have a Create button somewhere?

Good point, the mockup doesn't show this well. By default the Detail Page should show an Action button (see screenshot). If a user clicks Edit on an existing promo, they will see this page.

The user can also arrive on this page from the Listing Page by clicking Create New in the Actions Menu
<img width="651" alt="Screen Shot 2022-11-08 at 7 51 28 AM" src="https://user-images.githubusercontent.com/81580345/200569758-b4c2fe87-21ea-4755-9f30-3df083b7b1ef.png">

**Comment by vannguyenn** [comment]
@brendan-shea-pm Is this promotion name used internally or visible to customers? Do we need to separate the name (use internally) and the label (visible to end customers)? If so, should we add another field called `Promotion Label`? Thanks

**Comment by brendan-shea-pm** [comment]
Hi @vannguyenn this name will be internal only. The only customer facing part of the promo set up will be in the messages section (PLP,  PDP, Cart, and Terms Conditions)
