### ISSUE TITLE
As an operator I want indicate an Promotion Type that represents the kind of Action the promo will trigger

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#104]
- [ ] User can click a Promotion Type dropdown and see the following options (ignore parenthesis in UI, these are notes for backend)

- Cart Discount (Discount: Order)
- Item Discount (Discount: Item)
- Shipping Promotion (Discount: Shipping)

- [ ] When user selects the Promotion Type, the Promotion Detail Page options for Action and Trigger will reflect any options related to the chosen Type

Mockup: (Promotion Detail Page) https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523![Promotion Detail Page_Create.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/741874ec-aced-47d1-ad16-f2a285f4008e)

**Comment by brent-hoover** [comment]
We should discuss this as this list seems muddy

**Comment by brendan-shea-pm** [comment]
Clarified these with @zenweasel and we are now aligned. The Promotion Types represent a combination of the Action (Discount) and Parameter (Order, Item, Shipping)
