### ISSUE TITLE
As an operator when I create a new promotion, I want the system to assign it a unique numeric promotion ID

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#107]
When a user chooses to create (or duplicate a promotion) the system should automatically assign a promotion with a randomly generated up to 20 character numeric promotion ID so that the promotion is easily identifiable by internal systems

- [ ] User creates a new promotion and an ID is automatically assigned

- [ ] User duplicates a promotion and the new promotion has an ID automatically assigned

- [ ] 20 character max for ID

- [ ] No two promotions can have the same ID

- [ ] ID is shown in header of promotion detail page

Mockup: (Promotion Detail Page) https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523![Promotion Detail Page ID.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/1e7a40ba-69c1-443f-87ed-973e23b77f1e)

**Comment by brent-hoover** [comment]
@brendan-shea-pm 

So since 20 digits doesn't allow for creating a globally unique ID via randomization is there any reason we can't do a auto-incrementing numeric ID starting at 1?

So this will be a `referenceId` field that is seperate from the mongo _id field that is automatically created

**Comment by brendan-shea-pm** [comment]
I think that would work as long as you don't think there's any kind of security issues around having a short ID

**Comment by brent-hoover** [comment]
Completed
