### ISSUE TITLE
As an operator I want to be able to see promotions, or a list of only active ones, or a list of “upcoming” promotions

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#111]
Users should be able to filter the list based on some common presets, including Active, Upcoming, Disabled, View All, and Archived ( if user has See Archived Promotions permission)

- [ ] User can click a header and the list updates to show only promos with the relevant statuses
- [ ] Active view shows promos that are Enabled and have a Start date earlier than today, and an End date later than today
- [ ] Upcoming view shows promos that have a Start date after today
- [ ] Disabled view shows any promos that are currently Disabled
- [ ] View All shows all promos (except Archived)
- [ ] Archived promos should not appear in any view other than Archived

![Promotions Listing Page_TabFilters.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/6e077835-fd03-497a-b6a1-8b4d1370cd10)

**Comment by vannguyenn** [comment]
@brendan-shea-pm The statuses list here is different from issue #113 which are Active, Upcoming, Disabled, Past and All.
Also, regarding this statement `Archived view should only be available to Admins and shows all Archived promotions`
How do we define the Admins here? Currently, we're managing users based on group permission, we should define which groups are able to see the Archived list I think.

**Comment by brendan-shea-pm** [comment]
I agree @vannguyenn let's make See Archived Promotions a permission. @zenweasel Should Archived be a Status or is it a different kind of flag. Overall goal with it is so that user can remove promos from their list if they no longer need it. Also functions a soft delete for promos that, for what ever reason, users no longer need

**Comment by brent-hoover** [comment]
@brendan-shea-pm What does archived mean and what is the purpose of it? We don't have any sort of "status" flag on the promotion right now, do we want to add one?

**Comment by brendan-shea-pm** [comment]
> 

Overall goal with Archive is so that user can remove promos from their list if they no longer want to see it. I didn't want to ask for a Delete function as we'd want the record of the promo, so thought Archive could be a kind of soft delete. In terms of how it's built I'm open as long as it solves the soft delete need
