### ISSUE TITLE
As an operator I want to see a Promotions Listing page that lists my promotions so that I can easily find the promotion I’m looking for

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#113]
The purpose of this ticket is to capture the various features of the layout, other tickets will go more in depth on the individual feature functionality (eg Search, Action, Status etc)

**Acceptance Criteria:**

- [ ] User can see a list of Promotions in a table, with columns that display
- Name
- Promo ID
- Promo Type
- Action
- Start Date
- End Date
- Status (issue [6625](https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/reactioncommerce/reaction/6625))

- [ ] User can access tab navigation that links to filtered views of the table with the following options (issue [6623](https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/reactioncommerce/reaction/6623))
- Active
- Upcoming
- Disabled
- Past
- All

- [ ] User can access search to find the promo they are looking for

- [ ] User can access filters to find the promo they are looking for

- [ ] User can sort the list ascending / descending by clicking on table headers

- [ ] User can access an Actions dropdown menu (issue [6622](https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/reactioncommerce/reaction/6622))

- [ ] User can select individual promotions in the table or select All by clicking the checkbox in the header

- [ ] User can navigate the list using standard pagination functionality

- [ ] User can access the Promotion Detail Page by clicking the Promotion Name

Mockup Link: https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523

![Screen Shot 2022-11-06 at 10.59.00 AM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/bd21c627-51ad-427f-af39-9ecb10709b4e)

**Comment by vannguyenn** [comment]
@brendan-shea-pm 
- I can not access this link https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/reactioncommerce/reaction/6622. Also could we list out possible actions inside the Actions dropdown menu?
- Which columns can users do the sorting?
- Search and filters functionalities should be hidden for now I think like the Customers listing page, APIs are not ready yet.
- What happens when users select individual promotions? I mean after they select the rows. which actions will we support them?

**Comment by brendan-shea-pm** [comment]
The links must have broken when I moved the tickets to the Kinetic repo (I had originally created the in the MOC board by accident). Hope for now the ticket number will be enough info for the reference. Actions for dropdown should be 

- Create New
- Duplicate
- Enable
- Disable
- Archive

Sorting should be available on all columns

Agree it's ok to hide the search and filter functionality for now

The Actions are listed above. I missed one item that I'll add to the ticket, if a user clicks the Promotion Name they should be taken to the Promotion Detail Page

<img width="147" alt="Screen Shot 2022-11-08 at 8 02 10 AM" src="https://user-images.githubusercontent.com/81580345/200572053-26b9988d-a47f-4260-ba17-41c60f5f9c5c.png">

**Comment by vannguyenn** [comment]
Got you, thanks @brendan-shea-pm

**Comment by vannguyenn** [comment]
Hi @zenweasel, do we need to add support for pagination and sorting on the API side for the promotions endpoint?

**Comment by brent-hoover** [comment]
@vannguyenn As far as I know, that is already included

**Comment by brent-hoover** [comment]
https://github.com/reactioncommerce/reaction/blob/8064ea70b5c1ed816cdb3669405427848678402f/packages/api-plugin-promotions/src/resolvers/Query/promotions.js#L24

**Comment by vannguyenn** [comment]
Yes, but it does not support pagination/sorting params as input arguments. I might be wrong, and I'm working on `feat/promotions` branch.
![image.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/78fa2d18-54b2-4a02-992c-5a41542e7307)
