### ISSUE TITLE
As an admin I want to set a promotion as "Never Stackable" to restrict it from being combined with any other promotions

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#114]
Acceptance Criteria:
User can set a promotion as Never Stackable
Never Stackable promotions are applied only when no other promotions are present on a cart
If a customer attempts to trigger a Never Stackable promotion and it conflicts with existing promotions, the customer receives a prompt in the cart to choose which promotion to keep

**Comment by brent-hoover** [comment]
We need to talk about:
> If a customer attempts to trigger a Never Stackable promotion and it conflicts with existing promotions, the customer receives a prompt in the cart to choose which promotion to keep

Not sure this is doable in Milestone 1 as it is a really big scope increase.

**Comment by vannguyenn** [comment]
@brendan-shea-pm  Is this action inside the Actions dropdown menu?
