### ISSUE TITLE
As  an operator I want to be able to trigger a promotion based on the value of the cart 

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#119]
- [ ] User can choose the trigger "Cart value is great than" 

- [ ] User can indicate the numerical threshold for the cart value

- [ ] The cart value calculation does not include tax or shipping

- [ ] User can use inclusions and exclusions on the trigger to indicate which attributes of the cart should activate the trigger ([issue 120](https://github.com/reactioncommerce/kinetic/issues/120))

Mockup  (Promotions / Detail / Choose Trigger)  https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=c9z0pplx66ozEPgb-0
![Screenshot 2022-11-11 at 12 54 39 PM](https://user-images.githubusercontent.com/81580345/201400291-70b6ae0f-8e52-42af-96c1-363fbfd6ea68.png)

**Comment by brendan-shea-pm** [comment]
@zenweasel I think we agreed that we would not have a No Trigger option, can you  confirm? To me, if a promo has No Trigger, then it could never be activated and thus it could never cause the associated action for the promo

**Comment by brent-hoover** [comment]
I can't fathom a reason to have a no trigger promotion


> To me, if a promo has No Trigger, then it could never be activated and thus it could never cause the associated action for the promo

That is precisely correct

**Comment by brendan-shea-pm** [comment]
Ok great, I'll update the mockups
