### ISSUE TITLE
As an operator I want to define inclusions and exclusions for a trigger so that I can indicate which attributes should activate a trigger

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#120]
Users need the ability to control what kinds of attributes can trigger a promotion by including or excluding them and setting conditions for each. These rules can be different from the rules of the promo action.  For example, a cart value trigger could include Brand is Northface so that any Northface item's  value is included in the cart value  that triggers the promo, but the promo action (eg 10% Off) may exclude Brand is Northface so that Northface items are not discounted.

Each Condition should include an Attribute, Operator, and Value

- [ ] User can set inclusions and exclusion conditions for a trigger
- [ ] Inclusions and Exclusions default to including all attributes and values
- [ ] Explicit Inclusions take priority over exclusions, so if we have Include Mens Shoes and Exclude Footwear (Where Mens Shoes are included under Footwear) then Mens Shoes inclusion would override the broader Footwear exclusion on any Mens Shoes 
- [ ] Each inclusion or exclusion condition can be based on the following attributes
- Brand
- Class
- Tag (Category)
- Vendor ID
- Style ID
- SKU
- Price Type
  - Full Price
  - On Sale
  - On Clearance
- [ ] Each inclusion  or exclusion condition can be based on the following Operator
  -  Is (single value)
  -  Is Any Of (for multiple values, any match is ok)
- [ ] Each inclusion or exclusion condition can have multiple values that can be set by user (based on the Attribute selected previously)
- [ ] User can remove a condition of the inclusion or exclusion
  
  Mockup (Promotions / Detail / Trigger / Inclusions): https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=c9z0pplx66ozEPgb-0
![Screenshot 2022-11-11 at 12 15 28 PM](https://user-images.githubusercontent.com/81580345/201397760-26140154-a48d-4885-a24c-d5e92b7df3d9.png)
![Screenshot 2022-11-11 at 12 23 59 PM](https://user-images.githubusercontent.com/81580345/201397781-c37a37a8-d7a3-4de2-ba24-949cfe0e4c1a.png)

**Comment by brendan-shea-pm** [comment]
@zenweasel Curious to get your feedback on this one. Particularly around how we should handle conflicting inclusions and exclusions. Seems to me if we default to everything is included, then the explicit (user selected) inclusions should be the override to exclusions (eg a way to indicate a narrow subset of some broader attribute that is excluded) Please let me know if how I'm think  about it is in line with how it can work

**Comment by brent-hoover** [comment]
@vanpho93 Can correct me if I am wrong but I think it works like:

Scenario 1: (Get $10 off when you spend more than $10 on Nike)
Step 1: Entire product catalog is filtered by inclusions (include all Nike)
Step 2: Remaining items are filtered by exclusions (exclude Gift Cards)

I don't quite understand the scenario you are describing here with:
> Seems to me if we default to everything is included, then the explicit (user selected) inclusions should be the override to exclusions (eg a way to indicate a narrow subset of some broader attribute that is excluded)

Since one of the most common operations for exclusions is going to be do things like exclude Gift Cards and Clearance items, I can't foresee a reason you would want to ever override those.

There might be a way using the existing rules engine to construct rules to do more complicated combinations but I think we should try to focus on simplicity unless there are specific use cases in this Milestone that we are missing. But if you can give me a couple of examples of the types of rules you are envisioning let's try to sort them out.

**Comment by brendan-shea-pm** [comment]
Ok that's helpful thanks, so If a user doesn't set any inclusions or exclusions, does that mean all things are included or does it mean that all things are excluded? Trying to understand the default, I thought it was that all things are included.

**Comment by brent-hoover** [comment]
@brendan-shea-pm Yes you are correct. All things are included by default, so both inclusions and exclusions are used to reduce the scope of the promotion, so I guess in a way they are both sorts of exclusions, just different in the way they are defined.

@vanpho93 let me know if I am correct here

**Comment by vanpho93** [comment]
@zenweasel that's correct.

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm, regarding inclusion and exclusion conditions, should we allow multiple values when the operator is `Is`? As Brian suggested, when users select the operator `Is` for inclusion/exclusion conditions, we only allow a single value. Or we can just remove the `Is` operator and use `Is Any Of` for both multiple and single values. What do you think?

**Comment by brendan-shea-pm** [comment]
Hi @vannguyenn The intention of `Is` is that it captures only items that have all of the values listed after `Is`. I believe it would be an `AND` condition for the values. Whereas `Is Any Of` should include items that have any of the values lists (an `OR` condition for the values)

**Comment by vannguyenn** [comment]
![image.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/4fc098cf-85c7-4344-97b5-b0d188dc5937)
@brendan-shea-pm, in this case, the values depend on the properties. For example, how is it possible if users select `ID` property, `Is` operator and provide multiple values? How a product have multiple id values?

**Comment by brendan-shea-pm** [comment]
@vannguyenn Yes Brian's suggestion is correct, we should only allow a single value if the user selects `Is`, I'll update the description of this issue

**Comment by brendan-shea-pm** [comment]
@vannguyenn In Conditions when choosing a Property I'm only seeing Vendor, Product ID, and Title in the list rather than the properties specified in the ticket. Am I doing something wrong or missing something?

Brand
Class
Tag (Category)
Vendor ID
Style ID
SKU
Price Type

**Comment by vannguyenn** [comment]
@brendan-shea-pm, for now, we only support some of your list above, it's based on cart item properties. Here is the list on Kinetic
![Screen Shot 2023-01-06 at 14.03.32.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/e94a4090-af5e-4630-b2ab-db26722bb812)
c/c @zenweasel @vanpho93

**Comment by brent-hoover** [comment]
@vannguyenn Price Type should be added as Brian has added this to the cart. Currently for stock Reaction this will always be the same.

@brendan-shea-pm Brand is the same as Vendor in Reaction. As discussed Vendor ID, Style ID and Class, and SKU are not attributes available in Stock Reaction. These are custom attributes, so they will not be available during testing.

Any custom attributes that a customer has will be available once we have the ability to introspect the product which is being worked on by @sujithvn but is currently blocked. I think something that we need to figure out is if we want to have a way to define what subset of cart attributes should we filter on and do we want a way to define which those are. This would probably need to be something we do in the next milestone.

**Comment by brent-hoover** [comment]
Actually, if people want SKU in the cart they can add it via a custom transformation since it's not actually needed to process the cart.

**Comment by brent-hoover** [comment]
Added this issue which gives more details as to how this should work: https://github.com/reactioncommerce/kinetic/issues/164
