### ISSUE TITLE
As an operator I want to determine a limit  to the number of times a discount can be used by a customer

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#132]
- [ ] User can indicate a usage limit (numerical value) that sets a limit on the number of times a customer can use the discount

![percustomer.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/d2e78388-1c1e-4ace-b822-7d946f17781d)

**Comment by brent-hoover** [comment]
@brendan-shea-pm this ticket is fine but want to check again if we need this for milestone 1. If we don't would like to not moving it here

**Comment by vannguyenn** [comment]
Duplicate with #149?

**Comment by brent-hoover** [comment]
I think they are a little different. One is order and one is customer

**Comment by vannguyenn** [comment]
Move this to Blocked while waiting for API supports

**Comment by brendan-shea-pm** [comment]
@zenweasel This isn't a hard requirement for v.1 so I think we can put this in the backlog

**Comment by vannguyenn** [comment]
@brendan-shea-pm API already supported this so I think we can implement this in the sprint

**Comment by brendan-shea-pm** [comment]
Excellent! Thanks @vannguyenn
