### ISSUE TITLE
As an operator I want to Trigger a promotion based on an Item in the cart

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#138]
- [ ] User can choose the trigger "Item is in cart" 

- [ ] User can use inclusions and exclusions on the trigger to indicate which item(s) or item attributes should activate the trigger ([issue 120](https://github.com/reactioncommerce/kinetic/issues/120))

Mockup  (Promotions / Detail / Item Trigger)  https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=c9z0pplx66ozEPgb-0

![Screenshot 2022-12-11 at 2 19 57 PM](https://user-images.githubusercontent.com/81580345/206924207-a1d20ecb-0420-4fc8-8f0d-a6bab6c561f5.png)
![Screenshot 2022-12-11 at 2 22 21 PM](https://user-images.githubusercontent.com/81580345/206924277-d5c1173f-4fc6-4d33-8345-09113b09a6fe.png)

**Comment by vanpho93** [comment]
BE current does not support this yet, instead of checking if the cart contains some items, we can say required value of some items is bigger than a certain amount, can be bigger than 0.

so it's just the same as this one "As an operator I want to be able to trigger a promotion based on the value of the cart" but the amount required is 0.

https://app.zenhub.com/workspaces/moc-main-board-62fd8e881686130027eafc31/issues/gh/reactioncommerce/kinetic/119

**Comment by vanpho93** [comment]
Update:

We added another field `totalItemCount` before, so we can do this feature with `totalItemCount` > 0. Quite funny because I added this field just for demonstration but turns out we actually need it.

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm, do you want to add a numeric field beside this field to have the ability to add a number amount of items in the cart? Something like this.
![image.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/7f378b6a-1e81-49df-8249-08799cc521de)

**Comment by brendan-shea-pm** [comment]
@vannguyenn Yes that works. Could you add text to the left of the number field that reads "Number of items required in cart" so that it's clear what the number field represents?

**Comment by vannguyenn** [comment]
@brendan-shea-pm Sure will do. Thanks

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm Regarding the field label, I think we should do something like this for consistency and a better layout. WDYT?
![Screenshot 2023-01-10 at 15.41.30.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/ba7f453f-467d-4086-8eb3-580db542e98e)![Screenshot 2023-01-10 at 15.41.40.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/b2a95778-4642-47bd-ada4-4a14fea3b80b)

**Comment by brendan-shea-pm** [comment]
@vannguyenn Yes that is a more elegant solution, thanks! Is there some way to indicate that this is the minimum number of items required? Want to make sure the user understands that it is ItemCount equal to or great than the number. So if a user puts 1 but the customer has 2 then the promo is still triggered.

**Comment by vannguyenn** [comment]
@brendan-shea-pm  We can have a description under the field, our TextField component supports this
![image.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/b22f82b1-c3a2-44ec-91ff-7b644f90e1be)

**Comment by brendan-shea-pm** [comment]
@vannguyenn Yes I like it! Can we say "Minimum number of items required to trigger promotion"

**Comment by vannguyenn** [comment]
Sure, will update it
