### ISSUE TITLE
As an operator I want to select a Standard coupon as my trigger

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#142]
As a user I want to select a Standard coupon as the trigger for my promotion so that my promotion will be triggered by a standard coupon code

- [ ] User can choose the option "Coupon is used (Standard)" from the trigger menu

- [ ] Choosing this option causes the boxes of the Promotion Builder to show coupon name,  coupon code, in store, and inclusion / exclusion boxes in the UI

- [ ] Removing the trigger removes the boxes and returns the Promotion Builder to its default state

Mockup: Promotions / Detail Standard Coupon Trigger https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=DX1SCEHurQYZHXY8-0

![CouponIsUsedStandard](https://user-images.githubusercontent.com/81580345/208252544-ed080f66-6f8d-4d68-9d38-3524f9ff64c8.jpg)

**Comment by vannguyenn** [comment]
Move to blocked while waiting for API changes from Brian
