### ISSUE TITLE
As an operator I want to name my Standard coupon

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#144]
As an operator I want to name my Standard coupon so that I can refer to it in a user friendly way for internal purposes

- [ ] User can enter freeform text string to name the coupon
- [ ] UI shows "Give your coupon a name" about the field for typing the name
- [ ] User can edit this name on existing coupons

Mockup: Promotions / Detail Standard Coupon Trigger https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2038%3A58461&t=DX1SCEHurQYZHXY8-0

![CouponName](https://user-images.githubusercontent.com/81580345/208253600-6ac7fba2-82e7-4c74-b3d7-c03bb95a4ca0.jpg)

**Comment by vannguyenn** [comment]
Move to blocked while waiting for API changes from Brian
