### ISSUE TITLE
As an operator I want to create the Coupon Code that triggers my Standard Coupon

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#145]
As an operator I want to enter the Coupon Code that triggers my Standard Coupon so that I can create a user-friendly code for my customers

- [ ] User can enter an alphanumeric string in a field to define the coupon code

- [ ] The description above the field reads "Enter the coupon code (avoid characters like I, L, 0, and O)" but operator is not restricted from using those characters

- [ ] Coupon code characters should display in all caps

- [ ] Code should not be case sensitive

- [ ] Once a promotion is in window, the coupon code is not editable by any user

- [ ] An operator is prevented from saving a promotion with a coupon code that is a duplicate of a coupon code used in a different promotion _during an overlapping promotion window_ . In other words, an operator could have 2 different promotions with a coupon code "WELCOME" as long as the promotion Start and End dates do not overlap.

- [ ] If an operator tries to Save Changes on a promotion that contains a duplicate coupon code and that promotion overlaps the window with another promotion, they should see a warning that says "A promotion with this coupon code is already set to be active during part of this promotion window. Please either adjust your coupon code or your Promotion Start and End Dates

Mockup: Promotions / Detail Standard Coupon Trigger https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2038%3A58461&t=DX1SCEHurQYZHXY8-0
![CouponCode2](https://user-images.githubusercontent.com/81580345/208254058-a0757b98-aea0-44b4-8065-bb997ebb4162.jpg)

**Comment by vannguyenn** [comment]
Move to blocked while waiting for API changes from Brian
