### ISSUE TITLE
As an operator I want to flag my coupon so that it is also useable in store

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#146]
As an operator I want to flag my coupon so that it is also useable in store so that if my POS system is configured correctly it could identify the code and apply it in store. 

- [ ] User sees "Coupon can be used in store?" in promotions builder with a dropdown menu beneath it

- [ ] User can select either "Online Only" or "Online and In Store" as the options in the dropdown menu
- [ ] Menu defaults to Online Only

Mockup: Promotions / Detail Standard Coupon Trigger https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2038%3A58461&t=DX1SCEHurQYZHXY8-0
![InStore](https://user-images.githubusercontent.com/81580345/208254436-0bd8c105-aad0-41a1-be2c-5539f99f8ee4.jpg)

**Comment by vannguyenn** [comment]
Move to blocked while waiting for API changes from Brian
