### ISSUE TITLE
As an operator I want to limit how many times a promotion can been used on a single order

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#149]
As an operator I want to limit how many uses a promotion can have in a single order. For example the promotion offers $5 off Nike sneakers and the operator only wants the promotion to apply to one pair of shoes, they set the limit to 1. So a customer buying 3 pairs of Nike Shoes would only get $5 off a single pair rather than $5 off each of the 3 pairs (for a $15 total value)

- [ ] User can see a "Max # uses per order" field in the Promotion Usage Limits section of the Promotion Builder
- [ ] User can enter a numerical value in the field
- [ ] By setting this value, a custom cannot use the promotion more times than the number in this field allows within a given transaction

Mockup: Promotions / Detail Page https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=DX1SCEHurQYZHXY8-0

![perorder.jpg](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/0ca91f2b-cb46-4047-b95e-6fe4c03e8aa8)

**Comment by brent-hoover** [comment]
@brendan-shea-pm this ticket is a little confusing because the headline says "promotion can been used in a single order" but it seems like its how many items it can be applied to? Is that correct

**Comment by vannguyenn** [comment]
Move this to Blocked while waiting for API supports

**Comment by brendan-shea-pm** [comment]
Thanks @zenweasel I've updated the headline to better reflect this issue
