### ISSUE TITLE
As an operator I want to limit the maximum $ value that can be created by a promotion on a single order

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#150]
As an operator I want to limit the maximum $ amount discount that can be created by a promotion on a single order. 

For example, a promotion offers 10% discount on order but I want to limit the total possible value of the discount to $20. So if a customer spends $300 on an order and uses this promotion they would only receive a $20 discount rather than a $30 discount.

- [ ] User can see a "Max $ discount per order" field in the Promotion Usage Limits section of the Promotion Builder
- [ ] User can enter a numerical value in the field
- [ ] By setting this value, a customer cannot receive as discount from this promotion above the maximum value indicated

Mockup: Promotions / Detail Page https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=DX1SCEHurQYZHXY8-0

**Comment by brent-hoover** [comment]
@vannguyenn When you move something to blocked can you make sure and make a note why it is blocked. Is this because we need backend support?

**Comment by vannguyenn** [comment]
Yes, it is. Moved this to Blocked while waiting for API supports

**Comment by vannguyenn** [comment]
Ok, my bad I didn't see this field in the API documentation so I thought it does not support it. However, after discussing with @vanpho93, he suggests that `maximum $ amount discount` should belong to an action. @brendan-shea-pm Could we move this field out of `Promotion Usage Limits` section and move to inside the Actions section in `Promotion Builder`
![Screenshot 2023-01-12 at 08.20.40.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/c82e3732-2fce-4bc7-b0c4-f7b358988200)

**Comment by vannguyenn** [comment]
![image.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/a9364ae5-fed0-455e-8ef4-b14170888779)

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm, could you help to take a look at Ted's suggestion to see if that works? Thank you!
![Screenshot 2023-01-26 at 12.40.59.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/549ce3a4-9294-4b2c-bf82-76de9e621d4c)

**Comment by brendan-shea-pm** [comment]
Hi @vannguyenn I'm ok with changing Max to Maximum, although that's a very common English abbreviation. We should keep the rest of the labels as they are though, Total Uses doesn't let the user know whether that's for customer uses or order uses, Uses Per Customer doesn't indicate that they can use up to the amount entered, and Discount Amount Limit doesn't illustrate that it is a $ amount rather than a percentage for example. Good feedback though, thanks for checking

**Comment by brendan-shea-pm** [comment]
@vannguyenn As for moving it inside the Promotions Builder I'm fine with it, makes sense having it associated with the action
