### ISSUE TITLE
Kinetic to allow user to select a subset of available fields to use for filters

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/kinetic#153]
Kinetic can browse fields that are available on the cart via the new Introspection endpoint and then select which fields are available in the inclusion/exclusion. This could then be saved in AppSettings (?)

**Comment by brent-hoover** [comment]
I think this is a a duplicate of https://github.com/reactioncommerce/kinetic/issues/164. Do you agree @vannguyenn

**Comment by vannguyenn** [comment]
@zenweasel yes, agree with you. We can close this issue or #164
