### ISSUE TITLE
Kinetic Promotions: individual checkboxes cannot be selected, results in clicking through to promotion view

### ISSUE THREAD

**Issue by node82** [reactioncommerce/kinetic#154]
This loom for some reason is showing my mouse an inch to the right and does not convey the experience
but i have been able to reproduce the experience in Chrome, FireFox, and Safari

when wanting to do bulk actions, like bulk enable, utilizing the checkboxes of promotions to the left cannot be checked
![image](https://user-images.githubusercontent.com/26560026/209251192-080650ee-2216-4627-935d-5d86c50412cb.png)

the check all checkbox is accessible, 
but clicking on any of the checkboxes to the left of the promotion results in clicking into the promotion vs selecting the promotion while staying on the same screen

https://www.loom.com/share/9fc78f5bdbb44516b91cb7dcca2f0c82

**Comment by brent-hoover** [comment]
@node82 The PR you are checking is for the promotion detail only. The listing pages functionality is covered in other PR's

**Comment by vannguyenn** [comment]
@node82 this should work now on `trunk` branch. Could you try again? Thank you
