### ISSUE TITLE
Kinetic : Promotions : Date Selection

### ISSUE THREAD

**Issue by node82** [reactioncommerce/kinetic#160]
https://www.loom.com/share/7b8dabe646f947e68f49036131500435

when selecting a Start Date (Available From) and End Date ( Available To)
it selects the date right before that

example:  I select the 2023-01-25, and it sets it as 2023-01-24

will try it on a smaller monitor, the cursor I see on the monitor does not match the cursor in the loom video, so i wonder if having a widescreen is causing the issue... will test it out and follow up

**Comment by node82** [comment]
tried on different machine and different monitor, similar results, when selecting a date in January, i.e the 20th, it sets it as the 19th

**Comment by vannguyenn** [comment]
Hi @node82 I couldn't reproduce this on my end. Which branch did you use to test this issue? Could you try again on `trunk` branch to see if this's still an issue? Also, I suspect this could be a timezone issue, could I ask what is the store's timezone and your browser's timezone? I will try to reproduce this. Thanks

**Comment by node82** [comment]
it occurs on `trunk` and other branches as well ( `feat/duplicate-promotion` , `fix/ui-improvements` , etc ) 
Browsers Timezone is EST ( GMT -5)
Shop Timezone was set to PST (GMT -8) , I set it to EST, but am still experiencing when selecting a date, it sets it to a day prior

**Comment by vannguyenn** [comment]
I still couldn't reproduce it on my end, it might be an issue with the MUI library. I will do some research about this. In the meantime, @zenweasel could you help to check if this issue happens on your end when you have some time? Thanks

**Comment by node82** [comment]
i retested on `trunk` after [174](https://github.com/reactioncommerce/kinetic/pull/174) was merged, and am no longer experiencing the issue
