### ISSUE TITLE
As an operator I want my promotion to link to the Terms and Conditions so that customers can get more information about the promo

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#175]
- [ ] User sees a field with the label "Terms & Conditions URL" underneath the PDP Call to Action field in the Promotion Messaging section
- [ ] User can enter URL text in the T&C field
- [ ] Terms and Conditions URL is not required for saving the promotion

Mockup: Promotions / Detail Page https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=sFagdUnSMbq5ZIJn-0
![Screenshot 2023-01-29 at 4.30.43 PM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/602354a1-e78e-4281-a253-13b4590b905a)

**Comment by vannguyenn** [comment]
` Once promotion is saved, the URL text becomes a clickable link when viewing a promotion detail page (not in edit mode)`. 
@brendan-shea-pm Regarding this statement, the promotion details page is always in edit mode except when a promotion is active the field becomes disabled as uneditable.

**Comment by brendan-shea-pm** [comment]
Thanks @vannguyenn I updated the ticket to reflect your feedback, having the link active is not critical enough to make any changes around it so I removed that criteria
