### ISSUE TITLE
As an operator I want to create a Call to Action message a customer sees in the storefront PDP so that I can encourage customers to use the promotion

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#176]
- [ ] User sees a section with the header "Promotion Messaging"
- [ ] User sees a text field with the label "PDP Call to Action"
- [ ] User can enter text in the field
- [ ] User sees text near the field that indicates a "100 char max"
- [ ] User cannot enter more than 100 characters in the field
- [ ] User is notified when they reach the character limit

Mockups: Promotions / Detail Page https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=sFagdUnSMbq5ZIJn-0
![Screenshot 2023-01-29 at 4.30.43 PM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/ae10a26e-68d8-4b0e-a82a-8222effd518e)

**Comment by vanpho93** [comment]
* BE does not support this feature yet.
* BE can add these fields into promotion but Storefront needs a way to check if a promotion is applicable for the product. I am not sure how FE handle this requirement.
cc: @zenweasel

**Comment by vannguyenn** [comment]
@brendan-shea-pm Could you help to check @vanpho93 above comment? Thank you

**Comment by brendan-shea-pm** [comment]
@zenweasel what's the best way to tackle the storefront piece of this?

**Comment by brent-hoover** [comment]
@brendan-shea-pm I think I need more detail about what exactly this functionality is. We currently have no mechanism and have done no work or planning about doing anything on the PDP so I think there is a very good chance this is out of scope for this Open Source work.

In terms of just adding a piece of text to the Promotion that's not really difficult. But deciding when we display it on a PDP is quite difficult. Let me know if you want to have a quick call to talk this through to better understand it.

**Comment by brendan-shea-pm** [comment]
@zenweasel Yeah this issue is to ensure an operator has the ability to control the message a customer sees in the PDP about a promotion. Any storefront related tickets defining how that message should appear in a PDP would be created separately.

**Comment by brent-hoover** [comment]
@brendan-shea-pm Just want to clarify that it might involve more than just changes to Storefront to accomplish the feature of displaying promotion-related call to action on the PDP. There's a whole process for creating the data that is displayed there so simply making changes to the Storefront may not get the results wanted. Happy to add this field to the promotion though if that's all we want for now, so we will operate on this ticket with that understanding.

**Comment by brendan-shea-pm** [comment]
Thanks @zenweasel yes that's fine for this ticket, let's discuss the storefront stuff in our next weekly sync
