### ISSUE TITLE
As an operator I want to set my promotion type to Shipping Discount

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#177]
- [ ] User can select Shipping Discount in the Promotion Type dropdown
- [ ] When User has selected Shipping Discount as the Promotion Type, the Action Menu area of the promo builder updates to show:
      - [ ] Eligible Shipping Methods header
      - [ ] Label above Shipping Method field is "Include the following shipping methods"
      - [ ] Shipping Method field is empty

Mockup: Promotions / Detail Page 

Promotion Type Dropdown https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2082%3A47363&t=sFagdUnSMbq5ZIJn-0
![Screenshot 2023-01-29 at 4.18.31 PM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/423aae49-98bb-426d-9978-cffbb6e359ce)

Action Menu![Screenshot 2023-01-29 at 4.22.24 PM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/ea4477b8-bd09-4acd-bc35-a8435c3e8aa2)

**Comment by brent-hoover** [comment]
I think for matching Strings for Shipping Methods we might want add the ability to provide wildcards or regex? So that for dynamic shipping methods (e.g. UPS, FedEx, Shippo) if the provider makes a small change it won't break the promotion?

**Comment by brendan-shea-pm** [comment]
@zenweasel I think your comment is more relevant to https://github.com/reactioncommerce/kinetic/issues/179 Given those requirements do you think we're covered on this topic? If a user can see a list of Shipping Methods for the store when they click into the Shipping Methods field then I think we should be ol

**Comment by brent-hoover** [comment]
Closed via #195
