### ISSUE TITLE
As an operator I want to select the Shipping Method that I would like to use in the Promotion Action

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#179]
- [ ] User sees an "Eligible Shipping Methods" header beneath the discount amount section in Action menu
- [ ] User sees a label with the instructions: "Include the following shipping methods"
- [ ] User sees a list of available shipping methods for their shop when they click into the Shipping Methods field
- [ ] User sees autosuggested shipping methods for their shop when typing in the Shipping Methods field
- [ ] User can select multiple shipping methods
- [ ] User can remove a shipping method as long as the promotion is not Active

Mockup: Action Menus https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=2020%3A54523&t=pTW5WJEdTCCOAK70-0

![Screenshot 2023-01-29 at 4.22.24 PM.png](https://images.zenhubusercontent.com/63109e89e8b3c3d98a3f5897/e275306f-c359-4800-a84f-6f0eb3d6e864)

**Comment by brent-hoover** [comment]
@brendan-shea-pm The issue with this is that this works fine for the built in static methods we have in Reaction, but I am concerned about how it will work for dynamic methods from providers like UPS or Shippo. The methods are generated dynamically on the fly from the API based on a shipments weight and location (both FOB and destination) at checkout time so I am not sure how we would be able to generate a drop down list. Some APIs might have a call that will give you a list but I don't know if all will. 

Also I think this dynamic method will be far more common that the static methods we have built in.

**Comment by brent-hoover** [comment]
Closed via #195
