### ISSUE TITLE
As an admin I want to be able to create custom tax rates for country/region/postal

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/kinetic#47]
https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=1275%3A18359

**Comment by vannguyenn** [comment]
@brendan-shea-pm Hi Brendan, I think we're missing the wireframe for this ticket. The figma link in this ticket seems to be the same as https://app.zenhub.com/workspaces/kinetic-63156c24d5f91c00183040b5/issues/reactioncommerce/kinetic/46

**Comment by brendan-shea-pm** [comment]
Hi @vannguyenn You are correct, that is a link to the same wireframe because we don't have a mockup of the requested functionality. Please let me know if you need more info to complete

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm, I would need a wireframe to demonstrate the ticket's requirement, eg: How the screen should look with this functionality... This is a Front-end ticket, so a wireframe must be mandatory to start working on.

**Comment by vannguyenn** [comment]
Currently blocked because the wireframe is not ready
