### ISSUE TITLE
If a user does not have create shop permissions, do not prompt them to create a shop

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/kinetic#76]
Currently when you create a user, even if they don't have shop permissions, it will prompt you to create a shop and then tell you you don't have permissions. The system should be modified so that this step is skipped if you don't have permissions

**Comment by vannguyenn** [comment]
This issue will be resolved with issue https://app.zenhub.com/workspaces/kinetic-63156c24d5f91c00183040b5/issues/reactioncommerce/kinetic/75
