### ISSUE TITLE
Login screen references "Sign up" option that does not appear anywhere

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/kinetic#77]
If you enter an account that does not exist I get this message, however I am unable to locate a "Sign Up" option
![image.png](https://images.zenhubusercontent.com/59f21649a468affe6df846b8/a80b8e41-df8f-426e-bf07-e2bc59927ab9)

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm Could you advise me about the error message here? Currently, we're using the `Create your first shop` link as a way to sign up for an account. Should we change it to `Sign up` or should we update the error message? Thank you

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm Could you advise me about the error message here? Currently, we're using the `Create your first shop` link as a way to sign up for an account. Should we change it to `Sign up` or should we update the error message? Thank you

**Comment by brendan-shea-pm** [comment]
Hi @vannguyenn We should add a "Sign Up" button below Sign In so that users have a way to create an account if they don't have one.  In terms of the button style, if possible we should have a green (matching the Sign In green) stroke and green text, but the button should have a white background to differentiate it from the Sign In button. 

If that is not possible, please use the Cancel button style as the model and just change the text to "Sign Up"

**Comment by vannguyenn** [comment]
Got you. Should we also remove the text `Don't have a shop? Create your first shop`? Because we will use the Sign Up button to register an account.

**Comment by brendan-shea-pm** [comment]
Let's keep "Don't have a shop? Create your first shop" the way it is now. It's a good call to action if someone is specifically looking to create a shop.

**Comment by vannguyenn** [comment]
Hi @brendan-shea-pm , so I have 2 versions when adding the "Sign Up" button, what's your preference? The second version is similar to what we're having with the sign-up form. Thanks
![Screen Shot 2022-10-24 at 16.52.41.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/9a6efa7c-d71f-4acc-866f-b934837e53aa)![Screen Shot 2022-10-24 at 16.56.47.png](https://images.zenhubusercontent.com/63159bdb879d65d8327e4ee3/74707e5e-15d5-4822-a0bd-c0ac5cf1b823)

**Comment by brendan-shea-pm** [comment]
Great, thanks! The second one feels cleaner and more direct, Let's go with
that one. Two minor adjustments to format it to match the top sentence:

Change "Don't have an account" text color to black

Change "Sign Up" to bold text, leave it green
