### ISSUE TITLE
Customer Table Pagination

### ISSUE THREAD

**Issue by brendan-shea-pm** [reactioncommerce/kinetic#87]
As an operator, I want to navigate the records displayed in my Customer listing page's Customer Table through pagination so that I can expect the results to load quickly and in a volume that is preferable to me. I would like the option to choose the number of records displayed in the table:
- 10 (Default)
- 50
- 100
- 500

Figma: https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=1717%3A13491

Acceptance Criteria
- User can select the number of rows they see in a page (10, 50, 100, or 500) via a dropdown
- The number of results they select will persist through future sessions until they change it. (User selects 100 results, logs out, logs in again and when the Customer Table loads it loads 100 results)
- User can navigate to Previous and Next Page
- User can navigate to a page of their choice (this isn't included in the mockup, is there a preset component we can leverage for this?)

**Comment by vannguyenn** [comment]
I think we can reuse the existing pagination components in other tables and close this ticket. What do you think @brendan-shea-pm?

**Comment by brendan-shea-pm** [comment]
Good point @vannguyenn yes, let's use this pagination https://www.figma.com/file/vWot2cXXgjcsLpMq4SAX90/Kinetic?node-id=1276%3A22917
